In [65]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import necessary modules
from sklearn.model_selection import train_test_split

#Importing the dataset
dataset_train = pd.read_csv('train.csv')
dataset_test = pd.read_csv('test.csv')

In [66]:
dataset_train.rename(columns={'default payment next month':'default'}, inplace=True)

In [67]:
dataset_train.drop(['ID'], axis=1, inplace=True)

In [68]:
dataset_train

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0         100000    2          2         2   26     -1     -1     -1      0   
1         100000    1          2         1   47      0      0      2      0   
2          30000    2          2         2   23      3      3      3      3   
3         280000    2          1         2   31      2     -1     -1     -2   
4         210000    1          2         1   54      2     -1     -1     -1   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
26995      50000    1          2         2   32      0      0      0      0   
26996     200000    1          1         2   37      2      2      2      2   
26997      50000    1          1         2   26     -2     -2     -2     -2   
26998      70000    2          2         2   25      0      0      0      0   
26999     160000    2          2         1   36     -2     -2     -2     -2   

       PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0          0  ...       3542       1980       3980      4210      4159   
1          0  ...      64287      67838      66135      7000         0   
2          2  ...      29176      29958      30520      1200      1200   
3         -2  ...          0          0          0       168         0   
4         -1  ...        485        210       3483       176       195   
...      ...  ...        ...        ...        ...       ...       ...   
26995      0  ...      55957      29238       6119      2000      3000   
26996      2  ...     164182     169029     172084     13500      6000   
26997     -2  ...          0          0          0         0         0   
26998      2  ...      35122      28633      28039      3000      2000   
26999     -2  ...       2935       1603      14129         0      3660   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default  
0          1000      1080      2000      1525        0  
1          2500      5500         0      3000        0  
2             0      1400      1200         0        1  
3             0         0         0         0        0  
4           485         0      4466       417        0  
...         ...       ...       ...       ...      ...  
26995      1591        72      1134     73421        0  
26996         0      7500      6000      4000        1  
26997         0         0         0         0        0  
26998      4500      1200         0      1200        1  
26999      3135      1650     14200      1500        1  

[27000 rows x 24 columns]

In [69]:
y = dataset_train['default']
features = dataset_train.drop(['default'], axis=1, inplace=False)

In [70]:
dataset_train['EDUCATION'].unique()

array([2, 1, 3, 5, 4, 0, 6])

In [71]:
dataset_train['EDUCATION']=np.where(dataset_train['EDUCATION'] == 5, 4, dataset_train['EDUCATION'])
dataset_train['EDUCATION']=np.where(dataset_train['EDUCATION'] == 6, 4, dataset_train['EDUCATION'])
dataset_train['EDUCATION']=np.where(dataset_train['EDUCATION'] == 0, 4, dataset_train['EDUCATION'])

In [72]:
dataset_train['MARRIAGE'].unique()

array([2, 1, 0, 3])

In [73]:
dataset_train['MARRIAGE']=np.where(dataset_train['MARRIAGE'] == 0, 3, dataset_train['MARRIAGE'])
dataset_train.MARRIAGE.unique()

array([2, 1, 3])

In [74]:
( dataset_train['default'].value_counts() / len(dataset_train) ) * 100

0    77.862963
1    22.137037
Name: default, dtype: float64

In [75]:
features

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0         100000    2          2         2   26     -1     -1     -1      0   
1         100000    1          2         1   47      0      0      2      0   
2          30000    2          2         2   23      3      3      3      3   
3         280000    2          1         2   31      2     -1     -1     -2   
4         210000    1          2         1   54      2     -1     -1     -1   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
26995      50000    1          2         2   32      0      0      0      0   
26996     200000    1          1         2   37      2      2      2      2   
26997      50000    1          1         2   26     -2     -2     -2     -2   
26998      70000    2          2         2   25      0      0      0      0   
26999     160000    2          2         1   36     -2     -2     -2     -2   

       PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0          0  ...       4159       3542       1980       3980      4210   
1          0  ...      69111      64287      67838      66135      7000   
2          2  ...      29954      29176      29958      30520      1200   
3         -2  ...          0          0          0          0       168   
4         -1  ...        195        485        210       3483       176   
...      ...  ...        ...        ...        ...        ...       ...   
26995      0  ...      55739      55957      29238       6119      2000   
26996      2  ...     168386     164182     169029     172084     13500   
26997     -2  ...          0          0          0          0         0   
26998      2  ...      51152      35122      28633      28039      3000   
26999     -2  ...       3640       2935       1603      14129         0   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0          4159      1000      1080      2000      1525  
1             0      2500      5500         0      3000  
2          1200         0      1400      1200         0  
3             0         0         0         0         0  
4           195       485         0      4466       417  
...         ...       ...       ...       ...       ...  
26995      3000      1591        72      1134     73421  
26996      6000         0      7500      6000      4000  
26997         0         0         0         0         0  
26998      2000      4500      1200         0      1200  
26999      3660      3135      1650     14200      1500  

[27000 rows x 23 columns]

In [76]:
stdX = (features - features.mean()) / (features.std())              # standardization

X = dataset_train.drop(['default'], axis=1, inplace=False)
y = dataset_train['default']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
Xstd_train, Xstd_test, ystd_train, ystd_test = train_test_split(stdX, y, test_size=0.2, random_state=42)

In [104]:
from sklearn.model_selection import RandomizedSearchCV  # Randomized search on hyper parameters.
from sklearn.ensemble import RandomForestClassifier
param_dist = {'n_estimators': [50,100,150,200,250, 300],
               "max_features": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
               'max_depth': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
               "criterion": ["gini", "entropy"]}

rf = RandomForestClassifier()

rf_cv = RandomizedSearchCV(rf, param_distributions = param_dist,
                           cv = 5, random_state=0, n_jobs = -1)

rf_cv.fit(X, y)

print("Tuned Random Forest Parameters: %s" % (rf_cv.best_params_))

Tuned Random Forest Parameters: {'n_estimators': 200, 'max_features': 18, 'max_depth': 6, 'criterion': 'gini'}


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import seaborn as sns
Ran = RandomForestClassifier(criterion= 'gini', max_depth= 6,
                                     max_features= 18, n_estimators= 200,
                                     random_state=0)
Ran.fit(X_train, y_train)
y_pred = Ran.predict(X_test)
print('Accuracy:', metrics.accuracy_score(y_pred,y_test))

## 5-fold cross-validation
cv_scores =cross_val_score(Ran, X, y, cv=5)

# Print the 5-fold cross-validation scores
print()
print(classification_report(y_test, y_pred))
print()
print("Average 5-Fold CV Score: {}".format(round(np.mean(cv_scores),4)),
      ", Standard deviation: {}".format(round(np.std(cv_scores),4)))

plt.figure(figsize=(4,3))
ConfMatrix = confusion_matrix(y_test,Ran.predict(X_test))
sns.heatmap(ConfMatrix,annot=True, cmap="Blues", fmt="d",
            xticklabels = ['Non-default', 'Default'],
            yticklabels = ['Non-default', 'Default'])
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.title("Confusion Matrix - Random Forest");

Accuracy: 0.8257407407407408


In [ ]:
#Use model on test.csv and save as submission.csv with 2 columns: ID and default.payment.next.month
dataset_final_test = pd.read_csv('test.csv')
#Rename column
dataset_final_test.rename(columns={'ID   ':'ID'}, inplace=True)
#Predict output and store in a new column
dataset_final_test['default'] = Ran.predict(dataset_final_test.drop(['ID'], axis=1, inplace=False))
#Save as submission.csv
dataset_final_test[['ID','default']].to_csv('submission_out.csv', index=False)